[package]
name = "book-web-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "*"
config = "*"
once_cell = "*"
serde = "*"
serde_json = "*"
sqlx = { version = "*", features = ["runtime-tokio", "postgres"] }
thiserror = "*"
tokio = { version = "*", features = ["full"] }
tower-http = { version = "*", features = ["trace"] }
tracing = "*"
tracing-subscriber = "*"
