server:
    port: 8000

database:
    url: "postgresql://postgres:123456@localhost:5432/novel-web"

redis:
    url: "redis://127.0.0.1/"

logger:
    level: "debug"

data:
    path: "data/book"

auth:
    secret: "123456"
    access_token_duration: 15
    refresh_token_duration: 30

email:
    username: "xxxxxx@xx.xx"
    password: "xxxxx"
    host: "xxxx"
    port: 587